yarnPath: .yarn/releases/yarn-3.4.1.cjs
nodeLinker: node-modules
npmScopes:
  upfluence:
    npmRegistryServer: https://npm.pkg.github.com
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com
npmRegistries:
  //npm.fontawesome.com:
    npmAuthToken: ${FONTAWESOME_NPM_AUTH_TOKEN}
  //npm.pkg.github.com:
    npmAuthToken: ${GITHUB_TOKEN}
