sonar.projectKey=hyperevents
sonar.host.url=https://sonarqube.upfluence.co
sonar.organization=upfluence
sonar.sources=packages/hyperevents/src
sonar.javascript.lcov.reportPaths=packages/test-app/coverage/lcov.info
sonar.typescript.tsconfigPaths=packages/hyperevents/tsconfig.json,packages/test-app/tsconfig.json
sonar.coverage.exclusions=packages/hyperevents/src/_app_/**
sonar.cpd.exclusions=packages/test-app/tests/**,**/*-test.js,**/*-test.ts,**/test-support/**
sonar.tests=packages/test-app/tests
sonar.html.file.suffixes=.hbs
