#!/bin/sh

echo "[Pre-push hook triggered]"
echo ""
echo ""

echo "[1/2] Running the linter"
pnpm lint
if [ $? -ne 0 ]; then
 echo "[1/2] KO: Linter failed."
 echo "Aborting push."
 exit 1
fi
echo "[1/2] OK: Linter success"

echo ""
echo ""

echo "[2/2] Running ember tests"
pnpm --filter test-app exec ember test --silent -r dot

if [ $? -ne 0 ]; then
 echo "[2/2] KO: Ember tests have failed."
 echo "Aborting push."
 exit 1
fi
echo "[2/2] OK: Ember tests success"
exit 0
